language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master

after_success:
  - mkdir /home/travis/tmp
  - sudo $(which npm) install -g firebase-tools@2.0.2
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --token "$FIREBASE_TOKEN"; fi
